### ISSUE TITLE
Kamil, masz zły program.

### ISSUE THREAD

**Issue by piotrsawczuk** [kgnela/nwtaZ2#3]
2/10

**Comment by kgnela** [comment]
![kobieta](https://cloud.githubusercontent.com/assets/15333420/24109760/f1c41f52-0d91-11e7-868b-3c9dfa9a50b8.jpg)

**Comment by piotrsawczuk** [comment]
[https://github.com/kgnela/nwtaZ2/blob/master/zadanie1](url)

**Comment by piotrsawczuk** [comment]
[https://github.com/kgnela/nwtaZ2/blob/master/zadanie1](url)

**Comment by piotrsawczuk** [comment]
https://github.com/kgnela/nwtaZ2/blob/master/zadanie1

**Comment by piotrsawczuk** [comment]
Błąd rozwiazany.
